-- ===========================================================================
-- Tolaim — sample data
-- ===========================================================================
-- GENERATED FILE. Edit src/lib/data/seed-data.ts and run `npm run seed:gen`.
--
-- SAMPLE CONTENT — NOT A HALACHIC SOURCE. Every authority, rabbi, ruling and
-- alert below is invented for development. The organisation and rabbi names
-- are deliberately generic so nothing here can be mistaken for a real
-- published position. Replace all of it with reviewed content before launch:
--
--   delete from alerts; delete from rulings; delete from rabbis;
--   delete from authorities; delete from produce_items;
--
-- Everything is inserted as approved so a fresh project has a working public
-- site immediately. `approved_by` is null because no auth user exists yet.
-- ===========================================================================

begin;

-- Categories ---------------------------------------------------------------
insert into produce_categories (slug, name, sort_order) values
  ('leafy-greens', 'Leafy greens', 10),
  ('herbs', 'Fresh herbs', 20),
  ('cruciferous', 'Broccoli & cabbage family', 30),
  ('berries', 'Berries', 40),
  ('fruit', 'Fruit', 50),
  ('vegetables', 'Vegetables', 60),
  ('root-and-bulb', 'Roots & bulbs', 70),
  ('dried-and-grains', 'Dried goods & grains', 80)
on conflict (slug) do nothing;

-- Authorities --------------------------------------------------------------
insert into authorities (slug, name, short_name, kind, region, description, website_url, sort_order, status, approved_at) values
  ('metropolitan-produce-council', 'Metropolitan Rabbinical Produce Council', 'MRPC', 'organization'::authority_kind, 'North America', 'Publishes a seasonal produce guide covering the North American supply, updated twice a year from its own inspection laboratory.', null, 10, 'approved', now()),
  ('institute-produce-inspection', 'Institute for Produce Inspection', 'IPI', 'organization'::authority_kind, 'Israel', 'Laboratory-based inspection body working primarily with Israeli-grown produce, where infestation patterns differ substantially from imported supply.', null, 20, 'approved', now()),
  ('rav-yechezkel-adler', 'Rav Yechezkel Adler', 'R. Adler', 'posek'::authority_kind, 'North America', 'Widely cited on questions of produce inspection. Positions are recorded from written responsa and from rulings given to the communities that follow him.', null, 30, 'approved', now()),
  ('sefer-bedikas-hamazon', 'Sefer Bedikas HaMazon', 'SBH', 'publication'::authority_kind, 'International', 'A standard reference work on food inspection, now in its second edition. Cited by page number throughout this site.', null, 40, 'approved', now()),
  ('northern-vaad', 'Northern Vaad HaKashrus', 'Northern Vaad', 'organization'::authority_kind, 'United Kingdom', 'Issues guidance for the British and Northern European supply, which draws on different growing regions than the North American market.', null, 50, 'approved', now())
on conflict (slug) do nothing;

-- Produce ------------------------------------------------------------------
insert into produce_items (slug, name, also_known_as, category_id, summary, cleaning_guidance, season_note, image_path, image_alt, site_risk_level, status, approved_at) values
  ('romaine-lettuce', 'Romaine lettuce', array['Cos lettuce'], (select id from produce_categories where slug = 'leafy-greens'), 'Heavily infested with thrips and aphids that sit deep in the rib of the leaf.', 'Separate every leaf from the head — nothing can be checked while the head is intact. Soak the leaves in cold water with a small amount of vegetable wash, agitate, then rinse each leaf individually under a strong stream of water. Inspect both sides of each leaf against a light box, paying particular attention to the white rib, where thrips lodge and are hard to see.

If you have not been shown how to do this in person, buy pre-checked lettuce instead. This is the single most common item people believe they have cleaned properly and have not.', 'Infestation rises sharply in warm months and in field-grown rather than greenhouse supply.', null, 'Romaine lettuce', 2, 'approved', now()),
  ('iceberg-lettuce', 'Iceberg lettuce', array['Crisphead lettuce'], (select id from produce_categories where slug = 'leafy-greens'), 'The tight head protects the inner leaves, but the outer ones need real inspection.', 'Discard the outer leaves. Separate the remaining leaves, wash them, and inspect them against light. The inner core is generally clean, but do not assume the boundary between ''outer'' and ''inner'' — check until you have seen several consecutive clean leaves.', '', null, 'Iceberg lettuce', 3, 'approved', now()),
  ('spinach', 'Spinach', '{}', (select id from produce_categories where slug = 'leafy-greens'), 'Leaf miners tunnel inside the leaf itself, where washing cannot reach them.', 'Leaf miner damage shows as a pale winding trail inside the leaf. A leaf with visible trails is discarded — the insect is inside the leaf and no washing removes it. Wash the remaining leaves, then inspect each one against light for trails and for thrips along the stem.

Bagged ''triple-washed'' spinach has been washed, not inspected. It still requires checking unless it carries reliable supervision stating otherwise.', 'Leaf miner activity peaks in spring and early summer.', null, 'Spinach', 2, 'approved', now()),
  ('kale', 'Kale', array['Curly kale', 'Cavolo nero', 'Lacinato'], (select id from produce_categories where slug = 'leafy-greens'), 'The curled edges hold aphids tightly; flat-leaf varieties are easier.', 'Strip the leaves from the stems. Soak in cold soapy water and agitate vigorously — the curl is what makes this hard, and agitation is what dislodges what is caught in it. Rinse thoroughly, then inspect against light, opening out the curled edge as you go.

Flat-leaf varieties such as lacinato are meaningfully easier to check than curly kale.', '', null, 'Kale', 2, 'approved', now()),
  ('swiss-chard', 'Swiss chard', array['Silverbeet', 'Mangold'], (select id from produce_categories where slug = 'leafy-greens'), 'Both leaf miners and aphids; the thick stalk hides insects at the base.', 'Cut the leaf away from the stalk and treat the two separately. Discard leaves with miner trails. Wash and inspect the leaves against light. Split the stalks lengthwise and rinse the channel, which collects soil and insects.', '', null, 'Swiss chard', 2, 'approved', now()),
  ('arugula', 'Arugula', array['Rocket', 'Rucola'], (select id from produce_categories where slug = 'leafy-greens'), 'Small, tender leaves that hold aphids and are difficult to inspect one by one.', 'Soak in cold soapy water, agitate well, and rinse through a fine strainer. Because the leaves are small, inspect in small batches spread thinly on a light box rather than leaf by leaf. Check the strainer and the wash water — insects that were dislodged will be there.', '', null, 'Arugula', 2, 'approved', now()),
  ('parsley', 'Parsley', array['Flat-leaf parsley', 'Curly parsley'], (select id from produce_categories where slug = 'herbs'), 'Among the most heavily infested items in the produce aisle.', 'Cut the bunch free of its tie and separate the sprigs. Soak in cold soapy water for several minutes, agitating hard. Rinse through a fine cloth or mesh and examine what the cloth caught — for herbs this is the primary check, not an afterthought. Then inspect the sprigs themselves against light.

If the wash water comes back visibly dirty a second and third time, keep washing.', 'Consistently high year-round; not a seasonal item.', null, 'Parsley', 2, 'approved', now()),
  ('cilantro', 'Cilantro', array['Coriander leaf', 'Fresh coriander', 'Kusbara'], (select id from produce_categories where slug = 'herbs'), 'Similar to parsley and generally worse; the leaf shape traps insects.', 'Treat exactly as parsley: separate, soak in soapy water with hard agitation, filter the wash water through a cloth, inspect the cloth, then inspect the sprigs against light. Repeat the wash until the water runs clean.', '', null, 'Cilantro', 2, 'approved', now()),
  ('fresh-dill', 'Fresh dill', array['Dill weed'], (select id from produce_categories where slug = 'herbs'), 'The feathery fronds cannot be inspected reliably. Use dried or supervised frozen.', 'There is no home method that reliably clears fresh dill. The frond structure is too fine to inspect and too dense to wash through. Use dried dill, or frozen dill under reliable supervision, which is checked before freezing.

If a recipe calls for fresh dill, the supervised frozen product is the substitute — not a longer wash.', '', null, 'Fresh dill', 1, 'approved', now()),
  ('fresh-mint', 'Fresh mint', array['Nana', 'Spearmint', 'Peppermint'], (select id from produce_categories where slug = 'herbs'), 'Very heavily infested, and the textured leaf makes inspection unreliable.', 'Most authorities do not accept a home method for fresh mint. The leaf surface is ridged and matte, which hides insects that would be visible on a smooth leaf, and the plant is grown in conditions that favour infestation.

Use supervised pre-checked mint if you can find it; otherwise use dried.', '', null, 'Fresh mint', 1, 'approved', now()),
  ('basil', 'Basil', array['Sweet basil'], (select id from produce_categories where slug = 'herbs'), 'Thrips sit along the vein on the underside of the leaf.', 'Pick the leaves from the stems. Soak in cold soapy water, agitate, and rinse each leaf. Inspect the underside of every leaf against light, following the central vein — that is where thrips sit and they are the colour of the leaf.

Basil grown hydroponically under supervision is substantially cleaner and is the practical choice if you use it often.', '', null, 'Basil', 2, 'approved', now()),
  ('broccoli', 'Broccoli', '{}', (select id from produce_categories where slug = 'cruciferous'), 'The floret head is dense enough that insects inside it cannot be seen or reached.', 'Fresh broccoli heads cannot be checked by looking at them — the florets close over anything inside. The accepted method is to break the head into small florets, soak in warm soapy water long enough to drive insects out, agitate, and then filter and examine the wash water. This takes training to do reliably.

Frozen broccoli under reliable supervision is checked before freezing and is the ordinary choice for home kitchens.', 'Aphid loads rise in late summer and autumn.', null, 'Broccoli', 2, 'approved', now()),
  ('cauliflower', 'Cauliflower', '{}', (select id from produce_categories where slug = 'cruciferous'), 'Denser than broccoli and harder again; the head conceals everything inside it.', 'Cut the head into small florets — smaller than you think, because the point is to open the interior. Soak in warm soapy water, agitate hard, then filter the wash water through a cloth and examine it carefully. Repeat until the filter comes back clean.

Supervised frozen cauliflower is checked before freezing and avoids the whole procedure.', '', null, 'Cauliflower', 2, 'approved', now()),
  ('cabbage', 'Cabbage', array['Green cabbage', 'Red cabbage'], (select id from produce_categories where slug = 'cruciferous'), 'The tight head keeps the interior clean; the outer layers do not stay clean.', 'Remove and discard the outer leaves. Then peel off leaves one at a time, rinsing and checking each, until you reach leaves that are clean and tightly packed. From that point inward the head is generally reliable.

Check the base of each leaf where it met the core, which is where aphids collect.', '', null, 'Cabbage', 3, 'approved', now()),
  ('brussels-sprouts', 'Brussels sprouts', '{}', (select id from produce_categories where slug = 'cruciferous'), 'Small tight heads — the same problem as cabbage, at a scale that makes it slower.', 'Trim the base and remove the outer two or three leaves of each sprout. Halve or quarter them and rinse, checking the cut faces and between the remaining layers. Because each sprout is a separate head, this has to be done individually — there is no batch shortcut.', '', null, 'Brussels sprouts', 3, 'approved', now()),
  ('strawberries', 'Strawberries', '{}', (select id from produce_categories where slug = 'berries'), 'The seeded surface and the hull both hold insects, but they can be reached.', 'Cut off the green hull and a thin slice of the flesh beneath it — that hollow is the main problem area. Soak the berries in cold soapy water, agitate, and rinse each one under a stream of water while rubbing the surface with your thumb. Inspect the surface and the cut end against light.

Do not soak with the hull on; it traps what you are trying to remove.', 'Higher risk in peak local season; imported winter supply is usually cleaner.', null, 'Strawberries', 3, 'approved', now()),
  ('raspberries', 'Raspberries', '{}', (select id from produce_categories where slug = 'berries'), 'The hollow core and the gaps between drupelets cannot be cleared.', 'There is no reliable way to clean fresh raspberries. The berry is a cluster of small chambers around a hollow centre, and insects sit inside where neither water nor inspection reaches.

Use supervised frozen or processed raspberry product. A purée or preserve made under supervision has been dealt with before processing.', '', null, 'Raspberries', 1, 'approved', now()),
  ('blackberries', 'Blackberries', '{}', (select id from produce_categories where slug = 'berries'), 'Same structure as raspberries, with the same conclusion.', 'Not cleanable fresh, for the same reason as raspberries: the drupelet structure encloses spaces that cannot be reached or seen into. Use supervised frozen or processed product.', '', null, 'Blackberries', 1, 'approved', now()),
  ('blueberries', 'Blueberries', '{}', (select id from produce_categories where slug = 'berries'), 'Smooth-skinned and mostly clean, but the blossom end needs a look.', 'Rinse in a colander, agitating so the berries turn over. Spread them on a light surface and look over them — you are checking the small opening at the blossom end and for any berry that is soft or split. Discard damaged berries rather than trying to clean them.', '', null, 'Blueberries', 3, 'approved', now()),
  ('grapes', 'Grapes', array['Table grapes'], (select id from produce_categories where slug = 'fruit'), 'Generally clean; check where the fruit meets the stem.', 'Separate the grapes from the stem or open the bunch out, and rinse under running water. Look at the point where each grape attached to the stem and discard any that are split or mouldy. Bunches that arrive with visible webbing between the grapes are rejected rather than washed.', '', null, 'Grapes', 4, 'approved', now()),
  ('fresh-figs', 'Fresh figs', '{}', (select id from produce_categories where slug = 'fruit'), 'The fruit is hollow and its interior is not accessible for inspection.', 'Fresh figs cannot be checked without destroying the fruit, and opening every fig is not a practical method. Most authorities do not permit fresh figs without supervision.

Dried figs are a separate question — see the dried figs entry, where the fruit can be opened and looked at.', '', null, 'Fresh figs', 1, 'approved', now()),
  ('dried-figs', 'Dried figs', '{}', (select id from produce_categories where slug = 'dried-and-grains'), 'Open each fig and look inside; infestation happens in storage, not the field.', 'Tear or cut each fig open and look at the interior against good light. You are looking for small insects and for fine webbing, which is the clearer sign. A fig with webbing is discarded along with any others stored touching it.

Product that has been vacuum-packed or refrigerated since packing is markedly cleaner than loose bulk supply.', '', null, 'Dried figs', 3, 'approved', now()),
  ('dates', 'Dates', array['Medjool dates', 'Deglet Noor'], (select id from produce_categories where slug = 'dried-and-grains'), 'Open each date to remove the pit and look inside while you do.', 'You are already opening the date to remove the pit — do it in good light and look at the cavity and the flesh around it. Discard any date with visible insects, webbing, or a powdery residue.

Refrigerated or frozen supply is much less likely to be infested than dates kept at room temperature in bulk bins.', '', null, 'Dates', 3, 'approved', now()),
  ('rice', 'Rice', array['White rice', 'Basmati', 'Jasmine rice'], (select id from produce_categories where slug = 'dried-and-grains'), 'Spread it thin and look before cooking; storage pests are the concern.', 'Pour the rice in a thin layer onto a light-coloured tray and look across it — moving grains, small beetles, or clumped grains held together by webbing. Do this before the rice goes anywhere near the pot.

Rice kept sealed in a cool cupboard and used within a few months is rarely a problem. Long-stored open bags are where this shows up.', '', null, 'Rice', 3, 'approved', now()),
  ('celery', 'Celery', '{}', (select id from produce_categories where slug = 'vegetables'), 'Insects sit in the groove that runs the length of each stalk.', 'Separate the stalks from the base. Run your thumb down the inner groove of each stalk under running water — that channel is the whole issue. Check the leafy tops separately, or discard them; they are as infested as any leafy green.', '', null, 'Celery', 3, 'approved', now()),
  ('asparagus', 'Asparagus', '{}', (select id from produce_categories where slug = 'vegetables'), 'The overlapping scales at the tip hide insects and do not wash out.', 'Cut off the top inch or two, where the scales overlap tightly, and discard it. Rinse the remaining spear, rubbing along the shaft where smaller scales lie flat. Some authorities require the whole spear to be inspected under light after washing.', '', null, 'Asparagus', 2, 'approved', now()),
  ('artichoke', 'Globe artichoke', array['Artichoke'], (select id from produce_categories where slug = 'vegetables'), 'Layer upon layer of tightly packed leaves with no way to see between them.', 'Fresh whole artichokes are not accepted by most authorities. The bracts overlap so tightly that neither water nor light reaches between them, and taking the vegetable apart leaf by leaf is beyond what anyone does in practice.

Supervised frozen or jarred artichoke hearts are processed after checking and are the ordinary substitute.', '', null, 'Globe artichoke', 1, 'approved', now()),
  ('corn-on-the-cob', 'Corn on the cob', array['Sweetcorn'], (select id from produce_categories where slug = 'vegetables'), 'Strip the husk and silk and look at the tip, where the earworm enters.', 'Pull off the husk and all of the silk. Look at the tip of the cob — that is where corn earworm enters and where the damage is visible as chewed or discoloured kernels. Cut away any damaged section. Rinse the cob.', 'Earworm damage is most common in late-summer local corn.', null, 'Corn on the cob', 3, 'approved', now()),
  ('bell-peppers', 'Bell peppers', array['Capsicum', 'Sweet peppers'], (select id from produce_categories where slug = 'vegetables'), 'The outside is clean; cut it open and check the seed cavity.', 'Rinse the outside. Cut the pepper open and remove the seed core — look at the cavity and at the folds inside the flesh before you slice further. Discard any pepper with soft spots or entry holes on the skin.', '', null, 'Bell peppers', 3, 'approved', now()),
  ('cucumber', 'Cucumber', '{}', (select id from produce_categories where slug = 'vegetables'), 'Rinse it. Nothing further is required.', 'Rinse under running water. If the skin has soft spots or holes, cut them away or discard the cucumber — but ordinary graded supply needs nothing beyond a rinse.', '', null, 'Cucumber', 4, 'approved', now()),
  ('tomatoes', 'Tomatoes', array['Vine tomatoes', 'Cherry tomatoes'], (select id from produce_categories where slug = 'vegetables'), 'Rinse, and look at the stem scar.', 'Rinse under running water and glance at the scar where the stem attached, which is the one place anything collects. Split or mouldy fruit is discarded rather than washed.', '', null, 'Tomatoes', 4, 'approved', now()),
  ('carrots', 'Carrots', '{}', (select id from produce_categories where slug = 'root-and-bulb'), 'Scrub or peel. The root itself is not an infestation concern.', 'Scrub under running water or peel. Cut away any cracked or damaged section. The leafy tops, if attached, are treated as a leafy green and are usually discarded.', '', null, 'Carrots', 4, 'approved', now()),
  ('leeks', 'Leeks', '{}', (select id from produce_categories where slug = 'root-and-bulb'), 'Split lengthwise and rinse between the layers — soil and insects sit there.', 'Trim the root and the dark green tops. Split the leek lengthwise and fan the layers open under running water, rinsing between each one. The layers are sleeves and everything collects inside them; rinsing the outside does nothing.', '', null, 'Leeks', 3, 'approved', now()),
  ('scallions', 'Scallions', array['Spring onions', 'Green onions'], (select id from produce_categories where slug = 'root-and-bulb'), 'Same layered problem as leeks, at smaller scale.', 'Trim the roots and the tips. Split the green portion lengthwise and rinse inside the tube, where insects sit out of reach of a surface rinse. The white bulb needs its outer layer removed.', '', null, 'Scallions', 3, 'approved', now()),
  ('onions', 'Onions', array['Brown onions', 'Red onions'], (select id from produce_categories where slug = 'root-and-bulb'), 'Peel and use. Nothing is required.', 'Remove the papery skin and the first layer beneath it. Discard onions that are soft or have visible rot. Nothing further applies.', '', null, 'Onions', 5, 'approved', now()),
  ('potatoes', 'Potatoes', '{}', (select id from produce_categories where slug = 'root-and-bulb'), 'Scrub or peel; cut out any eyes or damage.', 'Scrub under running water or peel. Cut out sprouting eyes, green patches and any damaged flesh. There is no insect concern in sound potatoes.', '', null, 'Potatoes', 4, 'approved', now()),
  ('apples', 'Apples', '{}', (select id from produce_categories where slug = 'fruit'), 'Rinse, and cut out the core as you normally would.', 'Rinse under running water. Check the skin for entry holes — a small dark puncture usually means damage inside, and that apple is cut open or discarded. The core is removed in the ordinary course of eating.', '', null, 'Apples', 4, 'approved', now()),
  ('bananas', 'Bananas', '{}', (select id from produce_categories where slug = 'fruit'), 'Nothing required.', 'Peel and eat. The peel protects the fruit and there is no known concern.', '', null, 'Bananas', 5, 'approved', now()),
  ('avocado', 'Avocado', '{}', (select id from produce_categories where slug = 'fruit'), 'Nothing required beyond discarding fruit that is rotten inside.', 'Cut open and remove the pit. Discard flesh that is brown or rotten — that is a quality question, not an infestation one. Nothing else applies.', '', null, 'Avocado', 5, 'approved', now()),
  ('mushrooms', 'Mushrooms', array['Button mushrooms', 'Cremini', 'Portobello'], (select id from produce_categories where slug = 'vegetables'), 'Wipe or rinse; check the gills of open-cap varieties.', 'Wipe or rinse briefly. For open-cap varieties such as portobello, look at the gills underneath and discard any that are wet, dark and collapsing. Commercially grown mushrooms are raised in controlled conditions and are rarely a concern.', '', null, 'Mushrooms', 4, 'approved', now())
on conflict (slug) do nothing;

-- Positions ----------------------------------------------------------------
insert into rulings (produce_id, authority_id, risk_level, guidance, citation, effective_date, notes, status, approved_at) values
  ((select id from produce_items where slug = 'romaine-lettuce'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Leaf-by-leaf inspection over a light box after washing. Pre-checked product under reliable supervision is preferred for home use.', 'MRPC Produce Guide, 14th ed., §3.1', '2025-09-01'::date, '', 'approved', now()),
  ((select id from produce_items where slug = 'romaine-lettuce'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Field-grown romaine from the Israeli supply is not recommended in its fresh form. Use greenhouse-grown product under supervision.', 'IPI Bulletin 41', '2025-06-15'::date, 'Applies to open-field supply. Greenhouse product is treated at level 2.', 'approved', now()),
  ((select id from produce_items where slug = 'romaine-lettuce'), (select id from authorities where slug = 'rav-yechezkel-adler'), 2, 'May be checked at home by someone who has been trained. Washing without inspection is not sufficient.', 'Responsa, vol. II §17', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'romaine-lettuce'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 2, 'Requires washing followed by inspection of each leaf against strong light.', 'Sefer Bedikas HaMazon, 2nd ed., p. 112', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'iceberg-lettuce'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Discard outer leaves, wash and inspect the remainder. Within reach of a careful home cook.', 'MRPC Produce Guide, 14th ed., §3.2', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'iceberg-lettuce'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'Outer leaves removed; remaining leaves washed and checked.', 'Sefer Bedikas HaMazon, 2nd ed., p. 115', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'iceberg-lettuce'), (select id from authorities where slug = 'northern-vaad'), 2, 'Recent UK supply has shown aphid presence well into the head. Treat as expert checking.', 'Northern Vaad Produce Notice 2026/02', '2026-02-10'::date, '', 'approved', now()),
  ((select id from produce_items where slug = 'spinach'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Discard leaves showing miner trails; inspect the rest leaf by leaf against light.', 'MRPC Produce Guide, 14th ed., §3.4', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'spinach'), (select id from authorities where slug = 'institute-produce-inspection'), 2, 'Requires trained inspection. Pre-checked frozen product is the practical option for home kitchens.', 'IPI Bulletin 39', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'spinach'), (select id from authorities where slug = 'rav-yechezkel-adler'), 2, 'Checking is possible at home for one who knows what miner damage looks like.', 'Responsa, vol. II §19', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'kale'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Soak, agitate, rinse and inspect. Curly varieties require particular care at the leaf edge.', 'MRPC Produce Guide, 14th ed., §3.6', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'kale'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 2, 'Washing with agitation followed by inspection.', 'Sefer Bedikas HaMazon, 2nd ed., p. 121', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'kale'), (select id from authorities where slug = 'northern-vaad'), 3, 'May be checked at home following the soak-and-agitate method.', 'Northern Vaad Produce Guide, p. 8', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'swiss-chard'), (select id from authorities where slug = 'institute-produce-inspection'), 2, 'Leaf and stalk checked separately. Trained inspection required.', 'IPI Bulletin 44', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'swiss-chard'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Expert checking. Leaves with miner damage are discarded rather than cleaned.', 'MRPC Produce Guide, 14th ed., §3.7', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'arugula'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Wash with agitation, filter the wash water, inspect in thin batches.', 'MRPC Produce Guide, 14th ed., §3.9', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'arugula'), (select id from authorities where slug = 'rav-yechezkel-adler'), 2, 'Checking the wash water is an acceptable primary method for small-leaf greens.', 'Responsa, vol. II §22', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'parsley'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Wash with agitation, filter, inspect the filter cloth, then inspect the sprigs.', 'MRPC Produce Guide, 14th ed., §4.1', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'parsley'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended fresh. Use supervised pre-checked or frozen product.', 'IPI Bulletin 38', null, 'IPI''s position reflects the Israeli open-field supply specifically.', 'approved', now()),
  ((select id from produce_items where slug = 'parsley'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 2, 'Requires thorough washing and filtration of the wash water.', 'Sefer Bedikas HaMazon, 2nd ed., p. 138', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'parsley'), (select id from authorities where slug = 'northern-vaad'), 2, 'Expert checking. Pre-checked product widely available and preferred.', 'Northern Vaad Produce Guide, p. 12', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cilantro'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'As parsley. Filtering the wash water is required, not optional.', 'MRPC Produce Guide, 14th ed., §4.2', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cilantro'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended fresh.', 'IPI Bulletin 38', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cilantro'), (select id from authorities where slug = 'rav-yechezkel-adler'), 2, 'Permitted with thorough washing and filtration by one trained in the method.', 'Responsa, vol. II §24', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-dill'), (select id from authorities where slug = 'metropolitan-produce-council'), 1, 'Not recommended in fresh form. Use dried or supervised frozen.', 'MRPC Produce Guide, 14th ed., §4.5', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-dill'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended fresh.', 'IPI Bulletin 38', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-dill'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 1, 'Cannot be checked adequately.', 'Sefer Bedikas HaMazon, 2nd ed., p. 141', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-dill'), (select id from authorities where slug = 'rav-yechezkel-adler'), 2, 'Where fresh dill is genuinely needed, repeated washing with filtration by a trained checker may be relied upon.', 'Responsa, vol. II §26', null, 'A minority position; most authorities on this site do not permit fresh dill.', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-mint'), (select id from authorities where slug = 'metropolitan-produce-council'), 1, 'Not recommended fresh.', 'MRPC Produce Guide, 14th ed., §4.6', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-mint'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended fresh. Pre-checked product available under supervision.', 'IPI Bulletin 38', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-mint'), (select id from authorities where slug = 'northern-vaad'), 2, 'Expert checking permitted where supervised product is unavailable.', 'Northern Vaad Produce Guide, p. 14', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'basil'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Leaf-by-leaf inspection of the underside after washing.', 'MRPC Produce Guide, 14th ed., §4.8', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'basil'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 2, 'Washing and inspection required; hydroponic supply is preferable.', 'Sefer Bedikas HaMazon, 2nd ed., p. 144', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'basil'), (select id from authorities where slug = 'rav-yechezkel-adler'), 3, 'Hydroponic basil may be checked at home with a wash and a spot inspection.', 'Responsa, vol. III §4', null, 'Applies to hydroponic supply only.', 'approved', now()),
  ((select id from produce_items where slug = 'broccoli'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Break into florets, soak in warm soapy water, agitate, filter and examine the wash water.', 'MRPC Produce Guide, 14th ed., §5.1', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'broccoli'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Fresh broccoli heads are not recommended. Use supervised frozen product.', 'IPI Bulletin 40', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'broccoli'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 2, 'Requires the soak-and-filter method performed by a trained checker.', 'Sefer Bedikas HaMazon, 2nd ed., p. 156', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'broccoli'), (select id from authorities where slug = 'northern-vaad'), 2, 'Expert checking. Supervised frozen strongly preferred for home use.', 'Northern Vaad Produce Guide, p. 19', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cauliflower'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Small florets, warm soapy soak, agitation, filtration and examination of the wash water.', 'MRPC Produce Guide, 14th ed., §5.2', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cauliflower'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended fresh.', 'IPI Bulletin 40', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cauliflower'), (select id from authorities where slug = 'rav-yechezkel-adler'), 2, 'Permitted with the soak-and-filter method by a trained checker.', 'Responsa, vol. II §31', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cabbage'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Discard outer leaves, check successive leaves until consistently clean.', 'MRPC Produce Guide, 14th ed., §5.4', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cabbage'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'Outer leaves removed and successive leaves checked.', 'Sefer Bedikas HaMazon, 2nd ed., p. 160', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cabbage'), (select id from authorities where slug = 'institute-produce-inspection'), 2, 'Trained inspection recommended for open-field supply.', 'IPI Bulletin 40', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'brussels-sprouts'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Trim, remove outer leaves, halve and inspect each sprout.', 'MRPC Produce Guide, 14th ed., §5.5', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'brussels-sprouts'), (select id from authorities where slug = 'northern-vaad'), 3, 'Home checking, sprout by sprout.', 'Northern Vaad Produce Guide, p. 21', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'strawberries'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Hull removed, soaked, individually rinsed and rubbed, then inspected.', 'MRPC Produce Guide, 14th ed., §6.1', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'strawberries'), (select id from authorities where slug = 'rav-yechezkel-adler'), 3, 'Home checking following hull removal and individual rinsing.', 'Responsa, vol. II §35', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'strawberries'), (select id from authorities where slug = 'institute-produce-inspection'), 2, 'Trained inspection recommended; the surface seed cavities require magnification to clear reliably.', 'IPI Bulletin 42', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'strawberries'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'Washing with surface rubbing and inspection.', 'Sefer Bedikas HaMazon, 2nd ed., p. 171', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'raspberries'), (select id from authorities where slug = 'metropolitan-produce-council'), 1, 'Not recommended fresh.', 'MRPC Produce Guide, 14th ed., §6.3', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'raspberries'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended fresh.', 'IPI Bulletin 42', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'raspberries'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 1, 'Cannot be checked.', 'Sefer Bedikas HaMazon, 2nd ed., p. 174', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'raspberries'), (select id from authorities where slug = 'northern-vaad'), 1, 'Not recommended fresh.', 'Northern Vaad Produce Guide, p. 24', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'blackberries'), (select id from authorities where slug = 'metropolitan-produce-council'), 1, 'Not recommended fresh.', 'MRPC Produce Guide, 14th ed., §6.4', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'blackberries'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 1, 'Cannot be checked.', 'Sefer Bedikas HaMazon, 2nd ed., p. 174', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'blackberries'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended fresh.', 'IPI Bulletin 42', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'blueberries'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Rinse and inspect; discard soft or split berries.', 'MRPC Produce Guide, 14th ed., §6.5', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'blueberries'), (select id from authorities where slug = 'rav-yechezkel-adler'), 4, 'A rinse is sufficient for commercially graded supply.', 'Responsa, vol. III §9', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'blueberries'), (select id from authorities where slug = 'northern-vaad'), 3, 'Rinse and look over. Damaged fruit discarded.', 'Northern Vaad Produce Guide, p. 25', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'grapes'), (select id from authorities where slug = 'metropolitan-produce-council'), 4, 'Rinse. Reject bunches with webbing or mould.', 'MRPC Produce Guide, 14th ed., §7.2', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'grapes'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 4, 'Rinsing is sufficient.', 'Sefer Bedikas HaMazon, 2nd ed., p. 182', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'grapes'), (select id from authorities where slug = 'institute-produce-inspection'), 3, 'Open the bunch and check between grapes; mealybug has been found in some supply.', 'IPI Bulletin 43', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-figs'), (select id from authorities where slug = 'metropolitan-produce-council'), 1, 'Not recommended fresh without supervision.', 'MRPC Produce Guide, 14th ed., §7.4', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-figs'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended.', 'IPI Bulletin 43', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'fresh-figs'), (select id from authorities where slug = 'rav-yechezkel-adler'), 2, 'Each fig opened and inspected by a trained checker.', 'Responsa, vol. II §40', null, 'Practical only for small quantities.', 'approved', now()),
  ((select id from produce_items where slug = 'dried-figs'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Open each fig and inspect. Discard any showing webbing.', 'MRPC Produce Guide, 14th ed., §9.1', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'dried-figs'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'Each fruit opened and checked.', 'Sefer Bedikas HaMazon, 2nd ed., p. 201', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'dried-figs'), (select id from authorities where slug = 'northern-vaad'), 2, 'Bulk supply requires trained inspection; packaged supply may be checked at home.', 'Northern Vaad Produce Guide, p. 31', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'dates'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Open, pit and inspect each date.', 'MRPC Produce Guide, 14th ed., §9.2', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'dates'), (select id from authorities where slug = 'institute-produce-inspection'), 3, 'Each date opened and checked at the pit cavity.', 'IPI Bulletin 45', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'dates'), (select id from authorities where slug = 'rav-yechezkel-adler'), 3, 'Home checking on opening.', 'Responsa, vol. III §12', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'rice'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Spread thin on a light tray and inspect before use.', 'MRPC Produce Guide, 14th ed., §9.5', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'rice'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'Visual check of a thin layer.', 'Sefer Bedikas HaMazon, 2nd ed., p. 210', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'rice'), (select id from authorities where slug = 'rav-yechezkel-adler'), 4, 'Sealed commercial packaging within date requires no more than ordinary rinsing.', 'Responsa, vol. III §14', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'celery'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Stalks separated, groove rinsed and rubbed. Leafy tops treated as a leafy green.', 'MRPC Produce Guide, 14th ed., §8.1', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'celery'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'Each stalk rinsed along the groove.', 'Sefer Bedikas HaMazon, 2nd ed., p. 190', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'celery'), (select id from authorities where slug = 'northern-vaad'), 3, 'Home checking, stalk by stalk.', 'Northern Vaad Produce Guide, p. 27', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'asparagus'), (select id from authorities where slug = 'metropolitan-produce-council'), 2, 'Tips removed; remaining spear washed and inspected under light.', 'MRPC Produce Guide, 14th ed., §8.3', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'asparagus'), (select id from authorities where slug = 'institute-produce-inspection'), 2, 'Trained inspection required.', 'IPI Bulletin 44', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'asparagus'), (select id from authorities where slug = 'rav-yechezkel-adler'), 3, 'Removing the tip and rinsing thoroughly is sufficient at home.', 'Responsa, vol. III §16', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'artichoke'), (select id from authorities where slug = 'metropolitan-produce-council'), 1, 'Not recommended fresh. Use supervised frozen or jarred hearts.', 'MRPC Produce Guide, 14th ed., §8.5', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'artichoke'), (select id from authorities where slug = 'institute-produce-inspection'), 1, 'Not recommended.', 'IPI Bulletin 44', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'artichoke'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 1, 'Cannot be checked adequately in whole form.', 'Sefer Bedikas HaMazon, 2nd ed., p. 195', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'corn-on-the-cob'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Husk and silk removed; tip inspected and damage cut away.', 'MRPC Produce Guide, 14th ed., §8.7', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'corn-on-the-cob'), (select id from authorities where slug = 'northern-vaad'), 3, 'Home checking at the tip.', 'Northern Vaad Produce Guide, p. 29', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'bell-peppers'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Cut open and inspect the seed cavity.', 'MRPC Produce Guide, 14th ed., §8.9', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'bell-peppers'), (select id from authorities where slug = 'rav-yechezkel-adler'), 4, 'Rinse and remove the core; no further inspection required for graded supply.', 'Responsa, vol. III §18', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'bell-peppers'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'The interior cavity is checked on opening.', 'Sefer Bedikas HaMazon, 2nd ed., p. 197', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cucumber'), (select id from authorities where slug = 'metropolitan-produce-council'), 4, 'Rinse only.', 'MRPC Produce Guide, 14th ed., §8.11', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cucumber'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 4, 'Rinsing is sufficient.', 'Sefer Bedikas HaMazon, 2nd ed., p. 198', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'cucumber'), (select id from authorities where slug = 'institute-produce-inspection'), 4, 'Rinse only.', 'IPI Bulletin 44', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'tomatoes'), (select id from authorities where slug = 'metropolitan-produce-council'), 4, 'Rinse; discard split fruit.', 'MRPC Produce Guide, 14th ed., §8.12', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'tomatoes'), (select id from authorities where slug = 'northern-vaad'), 4, 'Rinse only.', 'Northern Vaad Produce Guide, p. 30', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'carrots'), (select id from authorities where slug = 'metropolitan-produce-council'), 4, 'Scrub or peel.', 'MRPC Produce Guide, 14th ed., §10.1', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'carrots'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 4, 'Washing is sufficient.', 'Sefer Bedikas HaMazon, 2nd ed., p. 205', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'leeks'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Split lengthwise and rinse between every layer.', 'MRPC Produce Guide, 14th ed., §10.3', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'leeks'), (select id from authorities where slug = 'institute-produce-inspection'), 3, 'Layers separated and rinsed individually.', 'IPI Bulletin 45', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'leeks'), (select id from authorities where slug = 'northern-vaad'), 3, 'Home checking between the layers.', 'Northern Vaad Produce Guide, p. 32', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'scallions'), (select id from authorities where slug = 'metropolitan-produce-council'), 3, 'Green tube split and rinsed inside; outer layer of the bulb removed.', 'MRPC Produce Guide, 14th ed., §10.4', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'scallions'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 3, 'Split and rinse the interior.', 'Sefer Bedikas HaMazon, 2nd ed., p. 207', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'onions'), (select id from authorities where slug = 'metropolitan-produce-council'), 5, 'No checking required.', 'MRPC Produce Guide, 14th ed., §10.6', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'onions'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 5, 'No concern.', 'Sefer Bedikas HaMazon, 2nd ed., p. 208', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'onions'), (select id from authorities where slug = 'institute-produce-inspection'), 5, 'No checking required.', 'IPI Bulletin 45', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'potatoes'), (select id from authorities where slug = 'metropolitan-produce-council'), 4, 'Scrub or peel.', 'MRPC Produce Guide, 14th ed., §10.7', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'potatoes'), (select id from authorities where slug = 'northern-vaad'), 4, 'Wash before use.', 'Northern Vaad Produce Guide, p. 33', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'apples'), (select id from authorities where slug = 'metropolitan-produce-council'), 4, 'Rinse; discard fruit with entry holes.', 'MRPC Produce Guide, 14th ed., §7.1', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'apples'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 4, 'Rinsing is sufficient for sound fruit.', 'Sefer Bedikas HaMazon, 2nd ed., p. 180', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'bananas'), (select id from authorities where slug = 'metropolitan-produce-council'), 5, 'No checking required.', 'MRPC Produce Guide, 14th ed., §7.7', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'bananas'), (select id from authorities where slug = 'sefer-bedikas-hamazon'), 5, 'No concern.', 'Sefer Bedikas HaMazon, 2nd ed., p. 186', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'avocado'), (select id from authorities where slug = 'metropolitan-produce-council'), 5, 'No checking required.', 'MRPC Produce Guide, 14th ed., §7.8', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'avocado'), (select id from authorities where slug = 'institute-produce-inspection'), 5, 'No checking required.', 'IPI Bulletin 43', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'mushrooms'), (select id from authorities where slug = 'metropolitan-produce-council'), 4, 'Rinse or wipe; check gills of open-cap varieties.', 'MRPC Produce Guide, 14th ed., §8.14', null, '', 'approved', now()),
  ((select id from produce_items where slug = 'mushrooms'), (select id from authorities where slug = 'northern-vaad'), 4, 'Rinse only for cultivated supply.', 'Northern Vaad Produce Guide, p. 30', null, '', 'approved', now())
on conflict (produce_id, authority_id) do nothing;

-- Rabbis -------------------------------------------------------------------
insert into rabbis (slug, name, community, region, description, default_authority_id, status, approved_at) values
  ('rabbi-shmuel-brandt', 'Rabbi Shmuel Brandt', 'Congregation Ohel Yaakov', 'North America', 'Follows the Metropolitan Rabbinical Produce Council guide across the board.', (select id from authorities where slug = 'metropolitan-produce-council'), 'approved', now()),
  ('rabbi-dovid-mizrachi', 'Rabbi Dovid Mizrachi', 'Sephardic Center of the Heights', 'North America', 'Follows the Institute for Produce Inspection, reflecting the community''s reliance on Israeli-grown produce.', (select id from authorities where slug = 'institute-produce-inspection'), 'approved', now()),
  ('rabbi-eliyahu-stern', 'Rabbi Eliyahu Stern', 'Beis Medrash of the North Side', 'North America', 'Follows the rulings of Rav Yechezkel Adler.', (select id from authorities where slug = 'rav-yechezkel-adler'), 'approved', now()),
  ('rabbi-menachem-roth', 'Rabbi Menachem Roth', 'United Synagogue, Northern District', 'United Kingdom', 'Follows Northern Vaad HaKashrus guidance for the British supply.', (select id from authorities where slug = 'northern-vaad'), 'approved', now()),
  ('rabbi-yosef-kahn', 'Rabbi Yosef Kahn', 'Kehilas Bnei Torah', 'International', 'Rules from Sefer Bedikas HaMazon as the community''s standard reference.', (select id from authorities where slug = 'sefer-bedikas-hamazon'), 'approved', now())
on conflict (slug) do nothing;

insert into rabbi_authority_overrides (rabbi_id, produce_id, authority_id, note) values
  ((select id from rabbis where slug = 'rabbi-dovid-mizrachi'), (select id from produce_items where slug = 'romaine-lettuce'), (select id from authorities where slug = 'rav-yechezkel-adler'), 'For locally grown romaine specifically, defers to Rav Adler.'),
  ((select id from rabbis where slug = 'rabbi-dovid-mizrachi'), (select id from produce_items where slug = 'strawberries'), (select id from authorities where slug = 'metropolitan-produce-council'), 'Follows the MRPC on North American strawberry supply.'),
  ((select id from rabbis where slug = 'rabbi-eliyahu-stern'), (select id from produce_items where slug = 'fresh-dill'), (select id from authorities where slug = 'metropolitan-produce-council'), 'Does not rely on the lenient position for fresh dill.'),
  ((select id from rabbis where slug = 'rabbi-yosef-kahn'), (select id from produce_items where slug = 'broccoli'), (select id from authorities where slug = 'institute-produce-inspection'), 'Holds that fresh broccoli heads should not be used at all.')
on conflict (rabbi_id, produce_id) do nothing;

-- Alerts -------------------------------------------------------------------
-- Dates are relative to when this file is run, so the demo always has live
-- alerts and a populated archive.
insert into alerts (slug, title, summary, body, severity, region, published_at, expires_at, status, approved_at) values
  ('thrips-surge-local-romaine', 'Thrips surge in local romaine — check twice this month', 'Field-grown romaine from local growers is running far heavier than usual. Wash and inspect twice.', 'Inspections this month have found thrips loads in locally grown romaine roughly three times the level recorded at the same point last year. The warm, dry spell through the growing period is the likely cause.

**What to do**

If you check romaine at home, run the full wash-and-inspect twice rather than once, and expect to find something. If you are not confident, switch to supervised pre-checked lettuce for the rest of the season.

Greenhouse-grown and hydroponic romaine is not affected and is running normally.

This notice will be reviewed at the end of the month.', 'urgent'::alert_severity, 'North America', now() + interval '-6 days', now() + interval '24 days', 'approved', now()),
  ('strawberry-season-opening', 'Local strawberry season is open', 'Peak-season local strawberries carry more than the imported winter supply. Hull and rinse individually.', 'Local strawberries have started arriving. Peak-season fruit consistently runs higher than the imported winter supply, and the difference is large enough to be worth noting.

**What to do**

Hull each berry, taking a thin slice of flesh with the hull, then soak and rinse the berries individually while rubbing the surface. Do not skip the hulling step before soaking — soaking with the hull on traps what you are trying to remove.', 'advisory'::alert_severity, 'North America', now() + interval '-19 days', now() + interval '70 days', 'approved', now()),
  ('dried-goods-storage-reminder', 'Warm-weather reminder: check stored dried goods', 'Storage pests multiply quickly in summer. Go through opened bags of rice, flour and dried fruit.', 'Storage pests breed fastest in warm weather, and an opened bag that was clean in March may not be clean in August.

**What to do**

Go through opened packets of rice, flour, dried fruit and nuts. Spread a sample thinly on a light-coloured tray and look across it for movement, for small beetles, and for grains held together by fine webbing. Anything showing webbing is discarded, along with anything stored touching it.

Moving dried goods to sealed containers in a cool cupboard prevents most of this.', 'info'::alert_severity, 'International', now() + interval '-33 days', now() + interval '45 days', 'approved', now()),
  ('cauliflower-supply-note-winter', 'Winter cauliflower supply running clean', 'This winter''s cauliflower is testing unusually clean, but the checking requirement has not changed.', 'Laboratory sampling of the current winter cauliflower supply has come back cleaner than the seasonal average.

This does not change what is required. A clean batch average does not tell you about the head in your kitchen, and the checking requirement for fresh cauliflower stands unchanged. The note is recorded here because people ask, and because a rumour that ''cauliflower is fine this year'' has been circulating.', 'info'::alert_severity, 'North America', now() + interval '-95 days', now() + interval '-12 days', 'approved', now()),
  ('aphids-uk-iceberg', 'Aphids found deep in UK iceberg lettuce', 'Northern Vaad has raised iceberg lettuce to expert checking for the British supply.', 'Northern Vaad HaKashrus has raised iceberg lettuce from home checking to expert checking for the British supply, following inspections that found aphids well past the outer leaves and into the head.

**What to do**

In the UK, treat iceberg as you would romaine: separate the leaves and inspect each one, or use supervised pre-checked product. Elsewhere the existing guidance is unchanged.', 'advisory'::alert_severity, 'United Kingdom', now() + interval '-41 days', now() + interval '-3 days', 'approved', now())
on conflict (slug) do nothing;

insert into alert_produce (alert_id, produce_id) values
  ((select id from alerts where slug = 'thrips-surge-local-romaine'), (select id from produce_items where slug = 'romaine-lettuce')),
  ((select id from alerts where slug = 'thrips-surge-local-romaine'), (select id from produce_items where slug = 'iceberg-lettuce')),
  ((select id from alerts where slug = 'strawberry-season-opening'), (select id from produce_items where slug = 'strawberries')),
  ((select id from alerts where slug = 'dried-goods-storage-reminder'), (select id from produce_items where slug = 'rice')),
  ((select id from alerts where slug = 'dried-goods-storage-reminder'), (select id from produce_items where slug = 'dried-figs')),
  ((select id from alerts where slug = 'dried-goods-storage-reminder'), (select id from produce_items where slug = 'dates')),
  ((select id from alerts where slug = 'cauliflower-supply-note-winter'), (select id from produce_items where slug = 'cauliflower')),
  ((select id from alerts where slug = 'cauliflower-supply-note-winter'), (select id from produce_items where slug = 'broccoli')),
  ((select id from alerts where slug = 'aphids-uk-iceberg'), (select id from produce_items where slug = 'iceberg-lettuce'))
on conflict do nothing;

commit;
